name: rtmp
description: A Dart library for RTMP (Real-Time Messaging Protocol).
version: 0.0.1
repository: https://github.com/kikuchy/rtmp

platform:
  - windows
  - linux
  - macos
  - android
  - ios

environment:
  sdk: ^3.10.4

dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
